### ISSUE TITLE
Decide on a minimum version of Python 3

### ISSUE THREAD

**Issue by dhermes** [dhermes/ndb-rewrite#30]
This was brought up in https://github.com/dhermes/ndb-rewrite/pull/27#discussion_r224878978 when asking why I didn't use f-strings.

f-strings were introduced in 3.6, so if we did this we'd have to drop 3.5 and `pypy3` (3.5.3) from the testing matrix.

**Comment by crwilcox** [comment]
Discussed with @theacodes . Let's continue to support 3.5+ which means no f-strs for now.
