### ISSUE TITLE
Django Middleware in its own package

### ISSUE THREAD

**Issue by chrisrossi** [dhermes/ndb-rewrite#33]
I wonder if the Django middleware doesn't belong in its own package. Rather than putting all the different framework integrations in the package with the library, it might make more sense to maintain each framework integration as a standalone package, each with its own stakeholders.

**Comment by dhermes** [comment]
@chrisrossi Jinx. I've discussed this with @crwilcox and @sduskis already and I think that's the way to go. I think this is probably true as well for `ndb.blobstore`, `ndb.metadata` and `ndb.stats`

**Comment by dhermes** [comment]
Closed for https://github.com/googleapis/google-cloud-python/issues/6255
