### ISSUE TITLE
Move this code in google-cloud-python

### ISSUE THREAD

**Issue by dhermes** [dhermes/ndb-rewrite#38]
/cc @theacodes @crwilcox 

I am trying to do this in a "clean" way. I used a script to move all the content into the `ndb/` subdirectory to match where it will end up in `google-cloud-python`:

```bash
# rewrite-history.sh
git filter-branch --prune-empty --tree-filter '
if [ ! -e ndb ]; then
    mkdir -p ndb
fi
git ls-tree --name-only $GIT_COMMIT | xargs -I files mv files ndb'
```

This is in the [`prepare-to-migrate`][1] branch. After doing this `$ git diff prepare-to-migrate:ndb master` comes back as identical, so I'm fairly happy with this.

Now that I have that branch, I can cherry-pick each commit into `google-cloud-python`. For example, the first commit:

```
$ git rev-list --max-parents=0 HEAD
bc8495bbfa718569c72493a73a4ca17623b7e442
$
$ git log -1 bc8495bbfa718569c72493a73a4ca17623b7e442
commit bc8495bbfa718569c72493a73a4ca17623b7e442
Author: Danny Hermes <daniel.j.hermes@gmail.com>
Date:   Wed Aug 29 09:50:26 2018 -0700

    Initial commit for `py3-rewrite`.

    This is a fresh branch intended to be used for a rewrite of
    ``ndb`` that is intended for Python 3.
$
$ git remote add gcp https://github.com/googleapis/google-cloud-python
$ git fetch gcp
$ git branch gcp-master gcp/master
$ git checkout gcp-master
$
$ git cherry-pick bc8495bbfa718569c72493a73a4ca17623b7e442
[gcp-master ae0fcbe833] Initial commit for `py3-rewrite`.
 Date: Wed Aug 29 09:50:26 2018 -0700
 4 files changed, 249 insertions(+)
 create mode 100644 ndb/AUTHORS
 create mode 100644 ndb/CONTRIBUTING.md
 create mode 100644 ndb/LICENSE
 create mode 100644 ndb/README.md
```

----

In the commit log, there are 8 references to issues or PRs in this repo:

```
$ git log | grep '\#'
    Complete the porting of the key module. (#24)
    Adding all arguments to Key() constructor. (#15)
    Adding skeleton interface for `key` and `model` modules. (#7)
    Adding skeleton interface for `tasklets` module. (#6)
    Relates to #2.
    Adding CI configuration. (#4)
    Adding basic nox configuration and simple test. (#3)
    Add package directory structure for `ndb`. (#1)
```

Should I:

1. Remove these
1. Modify these to point to this repo (I may delete this repo in the future, so maybe that's a bad idea)
1. Something else

----

References: https://unix.stackexchange.com/questions/280217/how-to-replay-git-repository-history-into-subdirectory

[1]: https://github.com/dhermes/ndb-rewrite/tree/prepare-to-migrate

**Comment by theacodes** [comment]
(1).

**Comment by dhermes** [comment]
Thanks @theacodes. I just cherry-picked them all and got rid of the references. They are now in the [`port-ndb-rewrite`][1] branch of my `google-cloud-python` fork.

To compare:

```
$ git remote -vv
gcp     git@github.com:dhermes/google-cloud-python.git (fetch)
gcp     git@github.com:dhermes/google-cloud-python.git (push)
origin  git@github.com:dhermes/ndb-rewrite.git (fetch)
origin  git@github.com:dhermes/ndb-rewrite.git (push)
$
$ git log -1 port-ndb-rewrite --pretty=%H
f491524a7779c1d616e2388a59308162ec309648
$ git log -1 master --pretty=%H
5bcb88e480db25ea564a56496da1359a2fff708f
$
$ git diff port-ndb-rewrite:ndb master  # Check identical
$
$ git log gcp/master..port-ndb-rewrite | grep '\#'  # All references removed
$
```

I filed https://github.com/googleapis/google-cloud-python/pull/6237 to bring this into `google-cloud-python`.

[1]: https://github.com/dhermes/google-cloud-python/tree/port-ndb-rewrite

**Comment by dhermes** [comment]
Resolved (i.e. the PR is merged)
